site_name: Interactive/API Documentation
site_url: https://NehaV20.github.io/Interactive-API-Documentation/
use_directory_urls: false

theme:
  name: material
  logo: assets/icon.png
  favicon: assets/favicon.ico
  features:
    - navigation.sections
    - navigation.expand

nav:
  - Introduction: index.md
  - Orders: 1.Orders.md
  - Trades: 2.Trades.md
  - Positions: 3.Positions.md
  - Signal: 4.Signals.md

extra_css:
  - css/custom.css

extra_javascript:
  - js/logo-link.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.extra
  - attr_list
